baseURL = "https://blog.saintic.com" # <head> 里面的 baseurl 信息，填你的博客地址
title = "一念博客" # 浏览器的标题
languageCode = "zh-cn" # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "mogege" # 主题 

paginate = 11 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt

uglyURLs = true
publishDir = "dist"

preserveTaxonomyNames = true

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    noreferrerLinks = true

[Permalinks]
    posts = "/:filename"

[menu]

    [[menu.main]]
        name = "Blog"
        url = "/blog.html"
        weight = 1

    [[menu.main]]
        name = "Note"
        url = "/note.html"
        weight = 2

    [[menu.main]]
        name = "Categories"
        url = "/categories.html"
        weight = 3

    [[menu.main]]
        name = "Tags"
        url = "/tags.html"
        weight = 4

    [[menu.main]]
        name = "Links"
        url = "/link.html"
        weight = 5

    [[menu.main]]
        name = "Baidu"
        url = "https://www.baidu.com/s?wd=site:blog.saintic.com+"
        weight = 6

    [[menu.main]]
        name = "Google"
        url = "https://www.google.com/search?q=site:blog.saintic.com+"
        weight = 7

[params]
    since = 2017
    author = "Hiroshi.tao"                          # Author's name
    avatar = "https://static.saintic.com/cdn/images/at.png!/fw/300" # Author's avatar
    subtitle = "记录技术点滴，开源项目与文档，分享经验与技术"                  # Subtitle
    home_mode = "" # post or other
    enableGitalk = false # gitalk 评论系统
    enableUtteranc = true # utteranc 评论系统

    google_verification = ""

    description = "一念博客，陶先森の博客，IT博客，技术记录与分享，开源项目与文档"
    keywords = "SaintIC,Hiroshi.tao,Blog,博客,Linux,DevOps,sys,python,go,js,vue,flask,picbed,sapic,Flask-PluginKit,rtfd" # site keywords

    beian = "京ICP备14058611号-1"
    baiduAnalytics = ""
    googleAnalytics = "" # Google 统计 id

    license= '本文采用 <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a> 进行许可'

    notice = "https://open.saintic.com/api/notice?catalog=4"

[params.utteranc]
    repo = "staugur/staugur.github.io" # The repo to store comments
    issueTerm = "pathname" # the mapping between blog posts and GitHub issues. 
    theme = "github-light" # Theme
    crossorigin = "anonymous" # default: anonymous

[params.social]
    github = "staugur"
    email = "me@tcw.im"
    qq = "1663116375"

[markup.goldmark.renderer]
    unsafe = true

[params.custom]
    js = ["js/my.js"]
